const tintColor = "#2f95dc";

export default {
	tintColor,
	tabIconDefault: "#ccc",
	tabIconSelected: tintColor,
	tabBar: "#fefefe",
	errorBackground: "red",
	errorText: "#fff",
	warningBackground: "#EAEB5E",
	warningText: "#666804",
	noticeBackground: tintColor,
	noticeText: "#fff",
	success: "#4DAD4A",
	successTransparent: "#4dad4a99",
	backgroundGrey: "#f7f7f7",
	lightGrey: "#F1F1F1",
	lightOrange: "#FFCB78",
	accentOrange: "#F7B05B",
	darkOrange: "#EE8A2A",
	brownOrange: "#CC5803",
	brownOrangeTransparent: "#cc580399",
	blackChocolate: "#1F1300",
	greyTransparent: "#56565699",
};
